name: 🚀 Feature / User Story
description: Propose a new "One Touch" feature or story
title: "[Story]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a new feature! Please ensure it aligns with the "One Touch" philosophy.
  - type: textarea
    id: story
    attributes:
      label: User Story
      description: As a [role], I want [feature], so that [benefit].
      placeholder: As a DBA, I want to click one button to rollback, so that I can sleep at night.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the specific conditions that must be met for this story to be "Done".
      placeholder: |
        - [ ] The CLI command `db rollback` exists
        - [ ] It completes within 30 seconds
        - [ ] No data loss occurs
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - 🔴 Critical (Blocker)
        - 🟡 High (Next Release)
        - 🟢 Medium (Backlog)
        - ⚪ Low (Nice to have)
    validations:
      required: true
  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Implementation Notes
      description: Any thoughts on how this should be built (Ansible, Python, etc.)?
